services:
  postgres-old:
    image: postgres:9.6
    environment:
      POSTGRES_DB: old_ckan_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "9133:5432"
    volumes:
      - postgres_old_data:/var/lib/postgresql/data
      - ./dump:/dump

volumes:
  postgres_old_data:
  postgres_new_data:
